name: Docker Build and Push

# OBRIGATÓRIO: Define que este arquivo é um workflow reutilizável
on:
  workflow_call:
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      REGISTRY_URL:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.REGISTRY_URL }}/sua-app:latest,${{ secrets.REGISTRY_URL }}/sua-app:${{ github.sha }}
